import Registration from '@/components/Registration';
import ProtectedRouteNoAuth from '@/components/ProtectedRouteNoAuth';

export const metadata = {
  title: 'Registration',
  description: 'Generated by create next app.',
};

export default function RegistrationPage(): JSX.Element {
  return (
    <>
      <ProtectedRouteNoAuth>
        <Registration />
      </ProtectedRouteNoAuth>
    </>
  );
}
