import Registration from '@/components/Registration';

export const metadata = {
  title: 'Login',
  description: 'Generated by create next app.',
};

export default function RegistrationPage(): JSX.Element {
  return (
    <>
      <Registration />
    </>
  );
}
