import { useTranslations } from 'next-intl';

export const metadata = {
  title: 'GraphiQL',
  description: 'Generated by create next app.',
};

export default function GraphiqlPage(): JSX.Element {
  const t = useTranslations();
  return (
    <>
      <h1>{t('graphiql')}</h1>
    </>
  );
}
