import Graphiql from '@/components/Graphiql';

export const metadata = {
  title: 'GraphiQL',
  description: 'Generated by create next app.',
};

export default function GraphiqlPage(): JSX.Element {
  return (
    <>
      <Graphiql />
    </>
  );
}
