import Login from '@/components/Login';

export const metadata = {
  title: 'Login',
  description: 'Generated by create next app.',
};

export default function LoginPage(): JSX.Element {
  return (
    <>
      <Login />
    </>
  );
}
