import Restfull from '@/components/Restfull';

export const metadata = {
  title: 'RESTfull',
  description: 'Generated by create next app.',
};

export default function RestfullPage(): JSX.Element {
  return (
    <>
      <Restfull />
    </>
  );
}
